config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pairings#index'

  resources :pairings, except: %i[edit index] do
    get 'inputs', to: 'pairings#new_inputs'
    get 'run', to: 'pairings#run'
    get 'official_base', to: 'pairings#official_file_input'
    get 'select_input_columns', to: 'pairings#select_input_columns'
    patch 'pairing_columns', to: 'pairings#pick_pairing_columns'
    patch 'official_base_save', to: 'pairings#save_official_file'
  end

  get 'inputs/official_files'
  get 'descriptions/abbreviations'
end

app/views/shared/_footer.html.erb
<footer class="bg-dark fixed-bottom">
  <div class="container offset-pt-4">
    <div class=" d-flex justify-content-center">
      <p class="m-3"><%= image_tag("CET-branco.png", style: 'height:50px;') %></p>
      <p class="m-3"><%= image_tag("Mobilidade.png", style: 'height:70px;') %></p>
      <p class="m-3"><%= image_tag("saude.png", style: 'height:60px;') %></p>
      <p class="m-3"><%= image_tag("BP_IGRS_Logo.png", style: 'height:50px;') %></p>
    </div>
    <div class=" d-flex justify-content-around">
      <p class="m-2 text-center text-white"> Versão 5.2.0 -- 31/08/2022 </p>
      <p class="m-2 text-center text-white"> <%= link_to "Repositório", "https://gitlab.com/pragmacode/vital-strategies-sadvt" %></p>
      <p class="m-2 text-center text-white"> <%= link_to "Licença AGPL v3.0", "https://gitlab.com/pragmacode/vital-strategies-sadvt/-/blob/master/COPYING" %></p>
    </div>
  </div>
</footer>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= css_class_for_flash_type(key) %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <% if value.is_a? Array %>
        <% value.each do |string| %>
          <li>
            <%= string %>
          </li>
        <% end %>
      <% else %>
        <li>
          <%= value %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to 'SPVT', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to t('.pairings'), root_path, class: 'nav-link' %></a>
        </li>

        <li class="nav-item">
          <%= link_to t('.official_files'), inputs_official_files_path, class: 'nav-link' %></a>
        </li>

        <li class="nav-item">
          <%= link_to t('.abbreviations'), descriptions_abbreviations_path, class: 'nav-link' %></a>
        </li>

        <% if current_user %>
          <% if current_user&.admin? %>
            <li class="nav-item">
              <%= link_to t('.admin'), trestle_path, class: 'nav-link' %></a>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to t('.logout'), destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('.login'), new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>