config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pairings#index'

  resources :pairings, except: %i[edit index] do
    get 'inputs', to: 'pairings#new_inputs'
    get 'run', to: 'pairings#run'
    get 'official_base', to: 'pairings#official_file_input'
    get 'select_input_columns', to: 'pairings#select_input_columns'
    patch 'pairing_columns', to: 'pairings#pick_pairing_columns'
    patch 'official_base_save', to: 'pairings#save_official_file'
  end

  get 'inputs/official_files'
  get 'descriptions/abbreviations'
end

app/models/pairing.rb
# frozen_string_literal: true

class Pairing < ApplicationRecord
  include AASM

  KINDS = %w[sat_sim sat_sih sat_sim_sih sat_sim_sih_samu infosiga_sim infosiga_sih infosiga_sim_sih
             infosiga_sim_sih_samu].freeze
  REQUIRED_INPUTS = {
    'sat_sim' => %w[sat_vehicles sat_victims sat_accidents sim],
    'sat_sih' => %w[sat_vehicles sat_victims sat_accidents sih],
    'sat_sim_sih' => %w[sat_vehicles sat_victims sat_accidents sim sih],
    'sat_sim_sih_samu' => %w[sat_vehicles sat_victims sat_accidents sim sih samu],
    'infosiga_sim' => %w[sim_with_doc infosiga],
    'infosiga_sih' => %w[sih infosiga],
    'infosiga_sim_sih' => %w[sim_with_doc sih infosiga],
    'infosiga_sim_sih_samu' => %w[sim_with_doc sih samu_with_doc infosiga]
  }.freeze

  validates :kind, presence: true, inclusion: { in: KINDS }
  validates :description, length: { maximum: 255 }

  has_many :outputs, dependent: :destroy
  has_many :inputs, dependent: :nullify
  accepts_nested_attributes_for :inputs

  has_paper_trail

  before_destroy :destroy_not_official_inputs

  aasm do
    state :created, initial: true
    state :input_validated, :running, :done, :errored

    event :validate_input do
      transitions from: :created, to: :input_validated
    end

    event :run do
      transitions from: :input_validated, to: :running
    end

    event :finish do
      transitions from: :running, to: :done
    end

    event :fail do
      transitions from: %i[created input_validated running], to: :errored
    end
  end

  def human_kind_name
    I18n.t "activerecord.attributes.pairing.kinds.#{kind}"
  end

  def required_input_types
    REQUIRED_INPUTS[kind].map { |name| InputType.find_by(name: name) }
  end

  def list_required_inputs
    list_inputs.where.not('input_types.name' => 'official_file').references(:input_type)
  end

  def official_base
    list_inputs.where('input_types.name' => 'official_file').references(:input_type)
  end

  def list_inputs
    Input.with_attached_file.where(pairing: self).includes(:input_type)
  end

  def list_outputs
    Output.with_attached_file.where(pairing: self)
  end

  def official_file?
    inputs.where(input_type: InputType.find_by(name: 'official_file')).length.positive?
  end

  def input_process_is_incomplete?
    inputs.count < required_input_types.length
  end

  def input_columns
    InputColumn.joins(:input).where('inputs.pairing_id' => id)
  end

  def group_columns_by_origin
    input_columns.includes(input: :input_type).group_by(&:input)
  end

  def selected_input_columns_titles
    columns = input_columns.where(selected: true).pluck(:title) << 'Score'
    columns.join(';')
  end

  private

  def destroy_not_official_inputs
    inputs.joins(:input_type).where.not(input_type: { name: 'official_file' }).destroy_all
  end
end

app/controllers/pairings_controller.rb
# frozen_string_literal: true

# rubocop:disable Metrics/ClassLength
class PairingsController < ApplicationController
  before_action :set_pairing_by_id, only: %i[show update destroy]
  before_action :set_pairing_by_pairing_id, except: %i[index new create show update destroy]
  before_action :check_write_access!, except: %i[index show select_input_columns]
  before_action :can_select_inputs_columns, only: [:select_input_columns]

  def index
    @pairings = Pairing.all.order(created_at: :desc)
  end

  def new
    @pairing = Pairing.new
  end

  def create
    @pairing = Pairing.new pairing_params

    if @pairing.save
      flash[:notice] = I18n.t('pairings.create.success')
      redirect_to pairing_inputs_path(@pairing)
    else
      flash.now[:error] = @pairing.errors.full_messages
      render :new
    end
  end

  def show; end

  def new_inputs
    @pairing.required_input_types.each do |type|
      build_input_with_type(type)
    end
  end

  def official_file_input
    input_type = InputType.find_by(name: 'official_file')
    official_file = Input.where(input_type: input_type, pairing: @pairing)
    @official_file_input = fetch_official_file_input(official_file, input_type)
  end

  def select_input_columns
    @columns = @pairing.group_columns_by_origin
  end

  def update
    build_inputs(@pairing, retrieve_inputs_attributes)
  end

  def save_official_file
    upsert_official_base(@pairing, retrieve_inputs_attributes)
  end

  def pick_pairing_columns
    selected_columns = params[:pairing] ? params[:pairing][:selected_columns] : nil
    save_pairing_columns(selected_columns)
  end

  def run
    if @pairing.input_validated?
      PairingJob.perform_later(@pairing.id)
      flash[:notice] = I18n.t('pairings.run.triggered_job')
      redirect_to root_path
    else
      flash[:error] = I18n.t('pairings.run.cannot_trigger_job')
      redirect_to pairing_path(@pairing)
    end
  end

  def destroy
    @pairing.destroy
    redirect_to root_path, notice: I18n.t('pairings.destroy.success')
  end

  private

  def pairing_params
    params.require(:pairing).permit(:kind, :description, inputs_attributes: %i[file input_type_id])
  end

  def set_pairing_by_pairing_id
    @pairing = Pairing.find(params[:pairing_id])
  end

  def set_pairing_by_id
    @pairing = Pairing.find(params[:id])
  end

  def build_input(pairing, input_type_id, file_hash)
    pairing.inputs.build(file: file_hash, input_type_id: input_type_id) if file_hash
  end

  def success_build(pairing)
    pairing.inputs.each(&:save)

    InputValidationJob.perform_later pairing.id if pairing.inputs.length == pairing.required_input_types.length

    flash[:notice] = I18n.t('pairings.update.success')
    render :show
  end

  def failed_build(pairing)
    flash[:error] = pairing.inputs.reject(&:valid?).map { |input| input.errors.messages }
    redirect_to pairing_inputs_path(pairing)
  end

  def build_inputs(pairing, inputs_params)
    inputs_params.each_value do |input_params|
      build_input(pairing, input_params['input_type_id'], input_params['file'])
    end

    if pairing.inputs.includes(:input_type, file_attachment: :blob).any? { |input| !input.valid? }
      failed_build(pairing)
    else
      success_build(pairing)
    end
  end

  def upsert_official_base(pairing, inputs_params)
    official_base = pairing.official_base.first
    if official_base
      official_base.update(file: inputs_params['0']['file'])
      redirect_to pairing_path(@pairing), notice: I18n.t('pairings.official_file_update')
    else
      build_inputs(pairing, inputs_params)
    end
  end

  def check_write_access!
    allow_access_for_a_condition(current_user.write_allowed?, 'only_managers_allowed')
  end

  def can_select_inputs_columns
    allow_access_for_a_condition(current_user&.can_select_input_columns?(@pairing), 'cannot_select_columns')
  end

  def build_input_with_type(type)
    @pairing.inputs.build(input_type: type) unless @pairing.inputs.exists?(input_type: type)
  end

  def redirect_to_root_path
    redirect_to root_path
  end

  def retrieve_inputs_attributes
    pairing_params[:inputs_attributes] || {}
  end

  def fetch_official_file_input(official_file_array, input_type)
    if official_file_array.empty?
      build_input_with_type(input_type)
    else
      official_file_array.first
    end
  end

  def allow_access_for_a_condition(condition, error_message_key)
    return if condition

    flash[:error] = I18n.t(error_message_key, scope: [:pairings])
    redirect_to root_path
  end

  def save_pairing_columns(selected_columns_id)
    update_input_columns(selected_columns_id) if selected_columns_id

    flash[:notice] = I18n.t('pairings.save_pairing_columns.success')
    redirect_to pairing_path(@pairing)
  end

  def update_input_columns(selected_columns_id)
    pairing_columns = @pairing.input_columns
    pairing_columns.includes([:input]).where(id: selected_columns_id).update(selected: true)
    pairing_columns.where.not(id: selected_columns_id).update(selected: false)
  end
end
# rubocop:enable Metrics/ClassLength

app/helpers/pairings_helper.rb
# frozen_string_literal: true

module PairingsHelper
  def options_for_pairing_kind_select
    options = [[]]

    options += Pairing::KINDS.map do |kind|
      [I18n.t("activerecord.attributes.pairing.kinds.#{kind}"), kind]
    end

    options
  end

  def file_type_to_upload(input_fields)
    type = I18n.t('activerecord.attributes.input_type.names')[input_fields.object.input_type.name.to_sym]
    "#{I18n.t('pairings.new_inputs.upload_message')} #{type}"
  end

  def trigger_button_class(pairing)
    pairing.input_validated? ? 'btn btn-success' : 'btn btn-success disabled'
  end

  def show_final_outputs(pairing)
    pairing.list_outputs.where(is_final: true)
  end

  def show_intermediate_outputs(pairing)
    pairing.list_outputs.where(is_final: false)
  end

  def display_upload_file?(input_fields)
    separate_conditions(
      true,
      [input_fields.object.persisted?, false]
    )
  end

  def upload_button_text(pairing)
    if pairing.official_file?
      '.update_official_file'
    else
      '.add_official_file'
    end
  end

  def show_upload_button?(pairing, user)
    separate_conditions(
      false,
      [pairing.input_process_is_incomplete? && user&.write_allowed?, true]
    )
  end

  def input_an_official_file?(input_fields)
    input_fields.object.input_type.name == 'official_file'
  end

  def separate_conditions(default_value, *scenarios)
    scenarios.each do |condition, return_value|
      return return_value if condition
    end

    default_value
  end
end

app/views/pairings/_pairing.html.erb
<div class='row border-top pt-1 mt-1'>
  <div class='col-md-3'><%= l pairing.created_at, format: :long %></div>

  <div class='col-md-2'><%= pairing.human_kind_name %></div>

  <div class='col-md-2'><%= pairing.aasm.human_state %></div>

  <div class='col-md-3'><%= pairing.description %></div>

  <div class='col-md-2 text-right'>
    <%= link_to t('.show'), pairing_path(pairing), class: 'btn btn-info btn-sm' %>

    <% if current_user&.write_allowed? %>
      <%= link_to t('.destroy'), pairing_path(pairing), data: { confirm: t('.are_you_sure') }, method: :delete, class: 'btn btn-danger btn-sm' %>
    <% end %>
  </div>
</div>

app/views/pairings/index.html.erb
<div class='container pb-4'>
  <h2 class='my-4'><%= t('.title') %></h2>

  <% if current_user&.write_allowed? %>
    <p><%= link_to t('.new'), new_pairing_path, class: 'btn btn-primary' %></p>
  <% end %>

  <div class='row font-weight-bold'>
    <div class='col-md-3'><%= Pairing.human_attribute_name :created_at %></div>

    <div class='col-md-2'><%= Pairing.human_attribute_name :kind %></div>

    <div class='col-md-2'><%= Pairing.human_attribute_name :aasm_state  %></div>

    <div class='col-md-3'><%= Pairing.human_attribute_name :description  %></div>

    <div class='col-md-2'></div>
  </div>

  <%= render partial: 'pairing', collection: @pairings, as: :pairing %>
</div>

app/views/pairings/new.html.erb
<%= form_with model: @pairing, local: true, class: 'container form-group pt-4' do |form| %>
  <div class="form-container pb-5">
    <h2><%= t('.title') %></h2>
  </div>

  <div class='form-group'>

    <div class='row g-3'>
      <div class='col-md-3'>
        <%= form.label :kind, class: 'form-label' %> <br>
        <%= form.select :kind, options_for_pairing_kind_select, class: 'col-form-select' %>
      </div>
    </div>

    <div class='row g-3'>
      <div class='col-md-3'>
        <%= form.label :description, class: 'form-label'%>
        <%= form.text_field :description, class: 'col-form-control'%>
      </div>
    </div>
  </div>

  <%= form.submit t('.save'), class: 'btn btn-primary' %>
<% end %>

app/views/pairings/new_inputs.html.erb
<%= form_with model: @pairing, local: true, class: 'container form-group pt-4' do |form| %>
  <div class="container pt-4">
    <div class="pb-5">
      <h2><%= t('.title') %> <%= @pairing.human_kind_name %> </h2>
    </div>
  </div>

  <%= form.hidden_field :kind, value: @pairing.kind %>

  <%= form.fields_for :inputs, @pairing.inputs do |input_fields| %>
    <% if display_upload_file?(input_fields) %>
      <div class="row m-4">
        <div class="col-md-10 custom-file">
          <%= input_fields.file_field :file, class: 'custom-file-input', lang: 'pt' %>
          <%= input_fields.label file_type_to_upload(input_fields), class: 'custom-file-label' %>
        </div>

        <%= input_fields.hidden_field :input_type_id %>
      </div>
    <% end %>
  <% end %>

  <%= form.submit t('.save'), class: 'btn btn-primary actions' %>
<% end %>

<%= javascript_tag do %>
  $(document).ready(function () {
    bsCustomFileInput.init()
  })
<% end %>

app/views/pairings/official_file_input.erb
<%= form_with model: @pairing, url: { action: :save_official_file, method: :patch }, local: true, class: 'container form-group pt-4' do |form| %>
  <div class="container pt-4">
    <div class="pb-5">
      <h2><%= t('.title') %> <%= @pairing.human_kind_name %> </h2>
    </div>
  </div>

  <%= form.hidden_field :kind, value: @pairing.kind %>

  <% if @official_file_input %>
    <%= form.fields_for :inputs, @official_file_input do |input_fields| %>
      <div class="row m-4">
        <div class="col-md-10 custom-file">
          <%= input_fields.file_field :file, class: 'custom-file-input', lang: 'pt' %>
          <%= input_fields.label file_type_to_upload(input_fields), class: 'custom-file-label' %>
        </div>

        <%= input_fields.hidden_field :input_type_id %>
      </div>
    <% end %>
  <% end %>

  <%= form.submit t('.save'), class: 'btn btn-primary actions' %>
<% end %>

<%= javascript_tag do %>
  $(document).ready(function () {
  bsCustomFileInput.init()
  })
<% end %>

app/views/pairings/select_input_columns.erb
<%= form_with model: @pairing, url: { action: :pick_pairing_columns, method: :patch }, local: true, class: 'container form-group pt-4' do |form| %>
  <div class="container pt-4">
    <div class="pb-5">
      <h2> <%= t('.title') %> </h2>
    </div>

    <div class="row d-flex justify-content-center pb-3">
      <div class="col-4">
        <p><%= link_to t('.back'), pairing_path(@pairing), class: 'btn btn-secondary' %></p>
      </div>

      <div class="col-4">
        <%= form.submit t('.save_pairing_inputs'), class: 'btn btn-primary actions' %>
      </div>
    </div>
  </div>

  <% @columns.each do |input, columns| %>
    <div class="py-2">
      <h4> <%= t('.file') %> <b><%= input.input_type.human_name %></b> </h4>
        <div class="py-3 form-check container d-flex">
          <div class="row">
            <% columns.each do |column| %>
              <div class="col-3">
                <%= form.check_box :selected_columns, { checked: column.selected, multiple: true, class: 'input_columns' }, column.id, nil %>
                <%= form.label :selected_columns, column.title %>
              </div>
            <% end %>
          </div>
        </div>
    </div>
  <% end %>
<% end %>

app/views/pairings/show.html.erb
<div class="container pt-4">
  <div class="pb-5">
    <h2><%= t('.title') %></h2>
  </div>

  <div class="row">
    <div class="col-4">
      <p><%= link_to t('.back'), root_path, class: 'btn btn-secondary' %></p>
    </div>

    <% if show_upload_button?(@pairing, current_user) %>
      <div class="col-4">
        <p><%= link_to t('.upload_inputs'), pairing_inputs_path(@pairing), class: 'btn btn-primary' %></p>
      </div>
    <% end %>

    <% if current_user&.write_allowed? %>
      <div class="col-4">
        <p><%= link_to t('.run'), pairing_run_path(@pairing), class: trigger_button_class(@pairing) %></p>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-2">
      <b><%= Pairing.human_attribute_name :created_at %>:</b>
    </div>

    <div class="col-md-10">
      <%= l @pairing.created_at, format: :long %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <b><%= Pairing.human_attribute_name :kind %>:</b>
    </div>

    <div class="col-md-10">
      <%= @pairing.human_kind_name %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <b><%= Pairing.human_attribute_name :aasm_state %>:</b>
    </div>

    <div class="col-md-10">
      <%= @pairing.aasm.human_state %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <b><%= Pairing.human_attribute_name :description %>:</b>
    </div>

    <div class="col-md-10">
      <%= @pairing.description %>
    </div>
  </div>

  <hr />

  <h3 class="py-1"><%= t('.chosen_columns') %></h3>

  <div id="accordion">
    <div class="card">
      <div class="card-header" role="tab" id="headingOne">
        <h4 class="mb-0">
          <a data-toggle="collapse" data-target="#collapseOne" href="collapseOne" aria-expanded="true" aria-controls="collapseOne">
            <span style="color: #0c0c0c"> <%= t('.accordion_title') %> </span>
          </a>
        </h4>
      </div>

      <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
        <div class="card-body">
          <div class="row d-flex justify-content-between">
            <div class="col-3"></div>
            <%= link_to(t('.set_selected_columns'), pairing_select_input_columns_path(@pairing), class: 'col-3 btn btn-primary') if current_user&.can_select_input_columns?(@pairing)  %>
            <div class="col-3"></div>
          </div>
          <% @pairing.group_columns_by_origin.each do |input, columns| %>
            <h4> <b> <%= input.input_type.human_name %></b> </h4>
            <div class="row pb-3">
              <% columns.each do |column| %>
                <% if column.selected %>
                  <div class="col-3">
                    <%= column.title %>
                  </div>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <hr>

  <div class="pb-5">
    <h3><%= t('.inputs') %></h3>
  </div>

  <div class="row">
    <%= render @pairing.list_required_inputs %>
  </div>

  <% if @pairing.official_base %>
    <div class="py-5">
      <h3><%= t('.official_base') %></h3>
    </div>

    <div class="row">
      <%= render @pairing.official_base %>

      <% if @pairing.done? && current_user&.write_allowed? %>
        <div class="col-4">
          <p><%= link_to t(upload_button_text(@pairing)), pairing_official_base_path(@pairing), class: 'btn btn-primary' %></p>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="pt-5 pb-3">
    <h3><%= t('.finals') %></h3>
  </div>

  <div class="row pb-5">
    <%= render show_final_outputs(@pairing) %>
  </div>

  <div class="pb-3">
    <h3><%= t('.intermediate') %></h3>
  </div>

  <div class="row pb-5">
    <%= render show_intermediate_outputs(@pairing) %>
  </div>
</div>